customhost = "database-1.cvembi5gsztk.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "tangjianxian-employee"
customregion = "us-east-1"
